### ISSUE TITLE
Implementation Roadmap

### ISSUE THREAD

**Issue by 95th** [95th/planview#1]
Case study on Angular training (Plan View)
- [x]	Registration
	- [x]	User should be able to register himself/herself to the application
		- [x]	First Name (Only Alphabets should be allowed)
		- [x]	Last Name (Only Alphabets should be allowed)
		- [x]	Date of Birth (Calendar field, should be less than current date)
		- [x]	Email address (domain name should be validated)
		- [x]	Address Line 1
		- [x]	Address Line 2
		- [x]	City (Only Alphabets should be allowed)
		- [x]	State (Only Alphabets should be allowed)
		- [x]	Country (Only Alphabets should be allowed)
		- [x]	Zip code (City should be validated against the Zip code)
		- [x]	Username
		- [x]	Password
		- [x]	Re-enter password (for confirmation) 
	- [x]	On successful registration, user should be redirected to dashboard
	- [x]	Implement the ADA concepts and add some animations on registration page load
- [x]	Login
	- [x] #2
	- [x]	On successful login, user should be redirected to dashboard
	- [x]	If 3 unsuccessful logins, after that lock the user
- [x]	(Admin) Dashboard
	- [x]	Message Inbox
		- [x]	Display message
	- [x]	Display submitted timesheet from user
	- [x]	List of users registered in the application should be listed
	- [x]	Table should contain “Edit/View”, “Unlock” and “Delete” options against each user
	- [x]	On click on the respective button, selected user should be edited/viewed/Unlock/deleted
	- [x]	Redirect to login if not authorized
- [x]	(Only Admin) Create work type
	- [x]	Work type code
	- [x]	Work type description
- [x]	(Only Admin) Create work item
	- [x]	Work item code
	- [x]	Work item description
	- [x]	Work type code (referential key to work type)
- [x]	(Only Admin) User/work item assignment
	- [x]	Select already created user
	- [x]	List all work item
	- [x]	Assign multiple work item to one user
	- [x]	Save
- [x]	(Admin/User) Send Message
	- [x]	To User
	- [x]	Subject (multiline)
	- [x]	Send button
- [x]	(Admin/User) Dashboard
	- [x]	Redirect to login if not authorized
	- [x]	Message Inbox
		- [x]	Display message
	- [x]	Assigned work item
		- [x]	Display assign work item
- [x]	User timesheet entry
	- [x]	Timesheet entry in multiple rows having following columns
		- [x]	Date (calendar)
		- [x]	Work item (drop down/ list only assign work item)
		- [x]	Hours
- [x]	Application log & Reporting
	- [x]	Capture all the Api calls with url/user details/timestamp
	- [x]	Generate weekly report with the name ‘Usability Report’ with the details
		- [x]	UserName
		- [x]	ApiName
		- [x]	Count (number of times user has accessed the url)
